#
# Blog Settings
#
author: Ignacio Calvo
description: Ignacio Calvo Blog
url: http://icalvo.github.io
title: Ignacio Calvo Blog
subtitle: A developer's musings
gravatar_url: https://s.gravatar.com/avatar/2a43aa43ba910dd1cd7620b8f4e57290
subscribe_rss: http://icalvo.github.com/tal

# Github repositories
github_user: icalvo
github_repo_url: https://github.com/icalvo/icalvo.github.io/

# Twitter
twitter_user: icalvo
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: icalvo
disqus_show_comment_count: true

# Google Analytics
# google_analytics_tracking_id: UA-177588-1


#
# Jekyll Settings
#
markdown: rdiscount
highlighter: pygments
permalink: /archive/:year/:month/:day/:title/
rdiscount:
  extensions: [smart]
paginate: 5
paginate_path: "page/:num"
category_dir: categories
