# USER SETTINGS
# ------------------------------------

# Blog Settings
author: Ignacio Calvo
description: Ignacio Calvo Blog
url: http://icalvo.github.io
title: Ignacio Calvo Blog
subtitle: A developer's musings
gravatar_url: https://s.gravatar.com/avatar/2a43aa43ba910dd1cd7620b8f4e57290
subscribe_rss: http://icalvo.github.com/tal

# Github repositories
github_user: icalvo
github_repo_url: https://github.com/icalvo/icalvo.github.io/

# Twitter
twitter_user: icalvo
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: icalvo
disqus_show_comment_count: true

# Google Analytics
# google_analytics_tracking_id: UA-177588-1


# JEKYLL SETTINGS
# ------------------------------------

# # Where things are
# source:       .
# destination:  ./_site
# plugins_dir:  _plugins
# layouts_dir:  _layouts
# data_dir:     _data
# includes_dir: _includes
# collections:
#   posts:
#     output:   true

# # Handling Reading
# safe:         false
# include:      [".htaccess"]
# exclude:      ["node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
# keep_files:   [".git", ".svn"]
# encoding:     "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# # Filtering Content
# show_drafts: null
# limit_posts: 0
# future:      false
# unpublished: false

# Plugins
# whitelist: []
gems: [jekyll-paginate-v2]

# Conversion
markdown: kramdown
highlighter: rouge
# lsi:         false
# excerpt_separator: "\n\n"
# incremental: false

# Outputting
permalink: /archive/:year/:month/:day/:title/

category_dir: categories
# timezone:      null

# quiet:    false
# verbose:  false
# defaults: []
# liquid:
#   error_mode: warn

# Markdown processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# Pagination
pagination:
  enabled: true
  per_page: 3
  paginate_path: /page:num
  sort_reverse: true
